- docs/adr/0005-use-custom-testeach-instead-of-jest-it-each.md
- src/refactorings/convert-if-else-to-ternary.test.ts
- src/refactorings/convert-ternary-to-if-else.test.ts
- src/refactorings/extract-variable.test.ts
- src/refactorings/flip-if-else.test.ts
- src/refactorings/flip-ternary.test.ts
- src/refactorings/inline-variable.test.ts
- src/refactorings/move-statement-down.test.ts
- src/refactorings/move-statement-up.test.ts
- src/refactorings/negate-expression.test.ts
- src/refactorings/remove-redundant-else.test.ts
- src/tests-helpers.ts
> Custom testEach() to replace Jest it.each()

- .travis.yml
- README.md
> Setup Travis config

- CHANGELOG.md
- src/editor/selection.ts
- src/refactorings/move-statement-down/move-statement-down.test.ts
- src/refactorings/move-statement-down/move-statement-down.ts
- src/refactorings/move-statement-up/move-statement-up.test.ts
- src/refactorings/move-statement-up/move-statement-up.ts
> Improve Move Statements on one-liners

- README.md
- package.json
- src/editor/error-reason.ts
- src/extension.ts
- src/refactorings/add-braces-to-if-statement/add-braces-to-if-statement.test.ts
- src/refactorings/add-braces-to-if-statement/add-braces-to-if-statement.ts
- src/refactorings/add-braces-to-if-statement/index.ts
> Issue #24: Add braces to if statement

- package.json
- src/editor/error-reason.ts
- src/extension.ts
- src/refactorings/simplify-ternary/index.ts
- src/refactorings/simplify-ternary/simplify-ternary.test.ts
- src/refactorings/simplify-ternary/simplify-ternary.ts
> Added simplify ternary refactoring

- src/refactorings/convert-ternary-to-if-else/convert-ternary-to-if-else.ts
- src/refactorings/convert-to-template-literal/convert-to-template-literal.ts
- src/refactorings/flip-if-else/flip-if-else.ts
- src/refactorings/flip-ternary/flip-ternary.ts
- src/refactorings/merge-if-statements/merge-if-statements.ts
- src/refactorings/merge-with-previous-if-statement/merge-with-previous-if-statement.ts
- src/refactorings/negate-expression/negate-expression.ts
- src/refactorings/react/add-braces-to-jsx-attribute/add-braces-to-jsx-attribute.ts
- src/refactorings/react/remove-braces-from-jsx-attribute/remove-braces-from-jsx-attribute.ts
- src/refactorings/remove-braces-from-arrow-function/remove-braces-from-arrow-function.ts
- src/refactorings/remove-redundant-else/remove-redundant-else.ts
- src/refactorings/replace-binary-with-assignment/replace-binary-with-assignment.ts
- src/refactorings/split-declaration-and-initialization/split-declaration-and-initialization.ts
- src/refactorings/split-if-statement/split-if-statement.ts
This is a continuation of #77 and #79.
> Refactored most refactorings to use the createVisitor pattern.

- src/editor/error-reason.ts
- src/extension.ts
- src/refactorings/convert-switch-to-if-else/convert-switch-to-if-else.test.ts
- src/refactorings/convert-switch-to-if-else/convert-switch-to-if-else.ts
- src/refactorings/convert-switch-to-if-else/index.ts
> New Refactoring: Convert Switch to If/Else

- src/refactorings/convert-switch-to-if-else/convert-switch-to-if-else.test.ts
- src/refactorings/convert-switch-to-if-else/convert-switch-to-if-else.ts
This PR outputs more natural if statements when all switch cases end with return statements.
> Switch to If/Else: continued

- CHANGELOG.md
- README.md
- package.json
- src/action-providers.ts
- src/commands.ts
- src/editor/adapters/create-vscode-editor.ts
- src/editor/adapters/vscode-editor.ts
- src/editor/adapters/vue-vscode-editor.ts
- src/editor/attempting-editor.test.ts
- src/editor/attempting-editor.ts
- src/editor/position.ts
- src/extension.ts
- src/refactorings/extract/index.ts
- src/refactorings/inline/index.ts
- src/refactorings/move-statement-up/move-statement-up.ts
Resolves #133
This yields interesting refactorings in the source code, but overall it was easy to implement:
> Support .vue files

- package.json
- src/editor/error-reason.ts
- src/extension.ts
- src/refactorings/extract-class/ClassNode.ts
- src/refactorings/extract-class/ClassRefactor.test.ts
- src/refactorings/extract-class/ClassRefactor.ts
- src/refactorings/extract-class/EXTRACT_CLASS_COMMAND.ts
- src/refactorings/extract-class/ExtractClassActionProvider.ts
- src/refactorings/extract-class/ExtractClassCommand.ts
- src/refactorings/extract-class/TextMatcher.test.ts
- src/refactorings/extract-class/TextMatcher.ts
- src/refactorings/extract-class/TypescriptClassNode.ts
- src/refactorings/extract-class/UmlNotation.test.ts
- src/refactorings/extract-class/UmlNotation.ts
- src/refactorings/extract-class/classNameMatcher.ts
- src/refactorings/extract-class/extract-class.test.ts
- src/refactorings/extract-class/extract-class.ts
- src/refactorings/extract-class/formatTs.ts
- src/refactorings/extract-class/index.ts
- src/refactorings/extract-class/parseClassDeclaration.ts
- src/refactorings/extract-class/utils/assert.ts
- tsconfig.json
- yarn.lock
Hi! Sorry I took so long.
I connect Extract Class refactoring to abracadabra. I skip implementations for RefactoringWithActionProvider and register command/provider directly. I hope you fix it yourself if needed.
There are some bugs for not trivial situations like class extraction from children class, getters/setters. But I don't have a definite solution. I will help with it if a issue opens.
> Extract class

- CHANGELOG.md
- src/array.ts
- src/ast/scope.ts
- src/editor/adapters/in-memory-editor.ts
- src/editor/editor-contract-test.ts
- src/editor/position.ts
- src/editor/selection.ts
- src/refactorings/extract/extract-type/extract-type.test.ts
- src/refactorings/extract/extract-variable/extract-variable.extractable-objects.test.ts
- src/refactorings/extract/extract-variable/extract-variable.ts
- src/refactorings/extract/extract-variable/occurrence.ts
- src/refactorings/extract/extract-variable/variable-declaration-modification.ts
> Re-use existing destructuring when extracting a variable

- src/refactorings/convert-for-to-foreach/convert-for-to-foreach.test.ts
- src/refactorings/convert-for-to-foreach/convert-for-to-foreach.ts
Resolves #92 
I'm new to the code base and AST/babel so let me know if there are some things you'd like me to change.
> Add For...of -> forEach refactoring for arrays

- src/refactorings/extract-interface/extract-interface.test.ts
- src/refactorings/extract-interface/extract-interface.ts
I gave it a try! Fixes https://github.com/nicoespeon/abracadabra/issues/425
> add support for generics for "extract interface"

- CHANGELOG.md
- src/refactorings/move-to-existing-file/move-to-existing-file.test.ts
- src/refactorings/move-to-existing-file/move-to-existing-file.ts
Closes #514
https://user-images.githubusercontent.com/1094774/156850806-5ecc4533-912e-4a9e-b105-f70f3dcb6509.mp4
> Move exported functions/types/interfaces to existing files

- CHANGELOG.md
- src/ast/scope.ts
- src/refactorings/move-to-existing-file/export-declaration.ts
- src/refactorings/move-to-existing-file/movable-node.ts
- src/refactorings/move-to-existing-file/move-to-existing-file.test.ts
- src/refactorings/move-to-existing-file/move-to-existing-file.ts
Closes #543
https://user-images.githubusercontent.com/1094774/157898902-629a8490-880a-4ab5-a659-fb1fac61bf50.mp4
> "Move to Existing File" on variable declarations

- src/playground/maths/calculator.ts
- src/playground/maths/maths.ts
- src/refactorings/change-signature/change-signature.test.ts
- src/refactorings/change-signature/change-signature.ts
Another one.
*This PR contains commits from* :  https://github.com/nicoespeon/abracadabra/pull/747
There are numerations for PR's Orders (I, II, III) _sorry combining commigs from differents PRS..._
Playground example
For Objects propertys I will search a good solution for it in a other iteration (I will take a break now :P)
> Change signature III: Handle class method

- README.md
* Fix link to toggle-highlights image
* Increase amount of refactorings
> Fix link to toggle-highlights image

- package.json
> perf: optimize activationEvents

- src/editor/adapters/in-memory-editor.ts
- src/editor/adapters/vscode-editor.ts
- src/editor/editor-contract-test.ts
- src/refactorings/change-signature/change-signature.test.ts
- src/refactorings/change-signature/change-signature.ts
> Fix "Change Signature" for nested functions

- src/action-providers.ts
Trying to execute a refactoring quick action in an untitled tab used to throw an error:
```
[error] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/Untitled-1'
at Function.e (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:26791)
at Object.readFile (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:25177)
at RefactoringActionProvider.isNavigatingAnIgnoredFile (/tmp/abracadabra/src/action-providers.ts:48:25)
at RefactoringActionProvider.provideCodeActions (/tmp/abracadabra/src/action-providers.ts:23:9)
at N.provideCodeActions (/opt/visual-studio-code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:44632)
```
Now it uses the text/lineCount from the …
> Fix action provider file ignore checks

- src/ast/scope.ts
- src/refactorings/inline/inline-variable/inline-variable.test.ts
> Fix inline variable with shadowed parameter

- .vscode/launch.json
- package.json
- src/extension.ts
- src/refactorings/convert-guard-to-if/convert-guard-to-if.test.ts
- src/refactorings/convert-guard-to-if/convert-guard-to-if.ts
- src/refactorings/convert-guard-to-if/index.ts
New refactoring: "Convert Guard to If"
Closes #794 
Unrelated to the issue, but I added a new debug launch configuration named "Run Current Test File".
It allows to run and debug a specific test file directly from VS Code by launching:
```bash
yarn test src/../current-file.test.ts
```
This was particularly helpful while developing the new refactoring.
Let me know if you prefer to remove it.
> Add "Convert Guard To If" refactoring

- src/refactorings/extract-parameter/extract-parameter.test.ts
- src/refactorings/extract-parameter/extract-parameter.ts
Following #1192
A small refactor to check at only one place if it's inside a function
I let you merge or close this PR if you don't want it, it's totally fine =)
> refactor DRY is function check
