nicoespeon/abracadabra

- CHANGELOG.md
- src/array-helpers.ts
- src/ast/domain.ts
- src/refactorings/flip-if-else/flip-if-else.test.ts
- src/refactorings/flip-if-else/flip-if-else.ts
- src/refactorings/inline-variable-or-function/inline-variable.ts
- src/refactorings/remove-redundant-else/remove-redundant-else.ts
Consider this guard clause example:
```js
function doSomething(someData) {
if (!isValid(someData)) {
return;
}
// … rest of the code
}
```
Before, running _Flip If/Else_ would have produced:
```js
function doSomething(someData) {
if (isValid(someData)) {
} else {
return;
}
// … rest of the code
}
```
Which is valid, but probably not what had in mind.
Now, it would produce the following result:
```js
function doSomething(someData) {
if (isValid(someData)) {
// … rest of the code
}
}
```
> Flip If/Else now handle guard clauses

- CHANGELOG.md
- package.json
- src/refactorings/extract-variable/extract-variable.basic-extraction.test.ts
- src/refactorings/extract-variable/extract-variable.extractable.test.ts
- src/refactorings/extract-variable/extract-variable.multiple-occurrences.test.ts
- src/refactorings/extract-variable/extract-variable.ts
- src/refactorings/extract-variable/extract-variable.variable-name.test.ts
- yarn.lock
Consider the following code:
```js
console.log("Hello World!");
```
If you extracted `"Hello World!"`, you would end up with the following code:
```js
const extracted = "Hello World!";
console.log(extracted);
```
And you'll be renaming the `extracted` symbol. Which is a quick and efficient way to extract the variable.
But now, it'll try to do a bit better. Now, you'll end up with:
```js
const helloWorld = "Hello World!";
console.log(helloWorld);
```
Which would make sense in that case, saving you the trouble of naming it!
Now, predicting the variable name is **hard**. Thus, you'll still be in "renaming mode", so it doesn't really matter if the guess is wrong. If it's correct though, it will certainly save you some more time in your refactoring, and that's the goal!
One last thing: if the …
> [Extract Variable] Infer variable name on String Literals

- CHANGELOG.md
- src/ast/transformation.ts
- src/refactorings/extract-variable/extract-variable.extractable.test.ts
- src/refactorings/extract-variable/extract-variable.ts
Consider the following code:
```js
console.log(session.user.address);
```
Before, extracting `address` would have produced:
```js
const address = session.user.address;
console.log(address);
```
This was fine… But it could be optimized. From our own experience, we always destructure the `address` property after the extraction.
Thus, from now on, extracting `address` will produce:
```js
const { address } = session.user;
console.log(address);
```
Since you end up renaming the symbol, you can provide a different name than `address` and it will work.
> Extract variable destructure member expressions properties

- src/refactorings/convert-to-template-literal/convert-to-template-literal.test.ts
- src/refactorings/convert-to-template-literal/convert-to-template-literal.ts
this should fix #73 by checking if the parent node of the current selection is an import statement.
> bugfix #73: add check for import statement

- .travis.yml
- package.json
- src/array-helpers.ts
- src/ast/domain.ts
- src/ast/transformation.test.ts
- src/ast/transformation.ts
- src/refactorings/convert-to-template-literal/convert-to-template-literal.ts
- src/refactorings/extract-interface/extract-interface.ts
- src/refactorings/inline-variable-or-function/find-inlinable-code.ts
- src/refactorings/inline-variable-or-function/find-param-matching-id.ts
- yarn.lock
Fixes #75
Maybe related to #87 
- Upgrade babel to latest version (7.8.7)
- Upgrade jest to latest version (25.1.0)
- Fix type issues and failing tests because of breaking changes
- Handle top-level awaits
- Add all compatible and missing babel plugins when parsing code to handle a maximum of scenario
> Upgrade @babel/parser

- src/action-providers.ts
- src/refactorings/simplify-ternary/index.ts
- src/refactorings/simplify-ternary/simplify-ternary.ts
- src/types.ts
This is a continuation of #77.
Please use #79 for discussion.
> Performance improvement (single AST traversal run)

- package.json
- yarn.lock
This seemed to fix the bug I mentioned over Twitter DMs, whereby `loc` was `null` for the call expression in `export default a(1);`.
I chose 7.9.4 because:
- that's the version used on AST explorer and I wasn't able to reproduce the bug there
- I had type errors when I tried to upgrade to the latest versions (7.10.x)
> Upgrade Babel parser to 7.9.4

- CHANGELOG.md
- src/ast/scope.ts
- src/editor/selection.ts
- src/refactorings/extract/extract-variable/extract-variable.multiple-occurrences.test.ts
- src/refactorings/extract/extract-variable/extract-variable.ts
- src/refactorings/extract/extract-variable/occurrence.ts
- src/refactorings/extract/extract-variable/variable-declaration-modification.ts
Fixes #97 
Consider:
```js
function brokenScenario() {
if (isValid) {
if (item.name == "sulfuras") {
}
}
console.log("sulfuras");
}
```
Trying to extract `"sulfuras"` before:
```js
function brokenScenario() {
if (isValid) {
const sulfuras = "sulfuras";
if (item.name == sulfuras) {
}
}
console.log(sulfuras);
}
```
Trying to do it now:
```js
function brokenScenario() {
const sulfuras = "sulfuras";
if (isValid) {
if (item.name == sulfuras) {
}
}
console.log(sulfuras);
}
```
🎉
> Extract variable/fix occurrences scope

- package.json
- src/editor/error-reason.ts
- src/extension.ts
- src/refactorings/convert-function-declaration-to-arrow-function/convert-function-declaration-to-arrow-function.test.ts
- src/refactorings/convert-function-declaration-to-arrow-function/convert-function-declaration-to-arrow-function.ts
- src/refactorings/convert-function-declaration-to-arrow-function/index.ts
Re. https://github.com/nicoespeon/abracadabra/issues/113
@nicoespeon ~The tests pass but the code action does not appear. What am I missing?~ Figured it out, the import in `extension.ts` was missing. Perhaps this should be part of the code generation?
P.S. your contributing guide is fantastic.
> Convert function declaration to arrow function

- CHANGELOG.md
- src/ast/identity.ts
- src/refactorings/extract/extract-variable/destructure-strategy.ts
- src/refactorings/extract/extract-variable/extract-variable.extractable-objects.test.ts
- src/refactorings/extract/extract-variable/extract-variable.extractable.test.ts
- src/refactorings/extract/extract-variable/extract-variable.ts
- src/refactorings/extract/extract-variable/occurrence.ts
Resolves #161
If a member expression can be destructured, it will now prompt the user to decide whether they want to destructure or preserve it. Default is for destructuring, as current behavior. But it would make it more convenient when destructuring is not needed.
> [Extract Variable] Ask destructure strategy

- src/refactorings/extract-class/TypescriptClassNode.test.ts
- src/refactorings/extract-class/TypescriptClassNode.ts
I found this bug in angular components and just fixed it.
> fix: "Extract Class" refactoring from class that implements multiple interfaces

- src/refactorings/split-declaration-and-initialization/split-declaration-and-initialization.test.ts
- src/refactorings/split-declaration-and-initialization/split-declaration-and-initialization.ts
Closes #232 
Adds a test to cover split declaration with TS annotation and fixes the duplication issue.
I'm not sure if my implementation is readable. I felt the need to add a comment to clarify why I create a new Identifier.
It's necessary, because if I reassign the `typeAnnotation` property to null, it mutates the Identifier node in the `variableDeclaration` too. I want the annotation to remain in the declaration, so I need to create a new Identifier and modify that.
Feel free to improve the implementation!
> Split declaration initialization / Fix TS Annotation Duplication

- CHANGELOG.md
- src/ast/domain.ts
- src/ast/scope.ts
- src/ast/transformation.ts
- src/refactorings/move-to-existing-file/move-to-existing-file.test.ts
- src/refactorings/move-to-existing-file/move-to-existing-file.ts
Closes https://github.com/nicoespeon/abracadabra/issues/265
Implement "Move to Existing File" for types & interfaces too! It works the same than for functions.
Thanks @ZakMiller for suggesting it 👍
> Move types & interfaces to existing files

- package.json
- yarn.lock
I didn't realized that Travis CI `.org` was deprecated and stopped building on June 15. Recent package upgrades weren't checked, and they may have broken CI.
I've migrated to Travis CI `.com` (which works), so now I want to put the main branch back into a working state.
> Revert some upgrades

- package.json
- src/ast/identity.ts
- src/ast/scope.test.ts
- src/ast/scope.ts
- src/ast/selection.ts
- src/ast/switch.ts
- src/ast/transformation.ts
- src/refactorings/convert-for-to-foreach/convert-for-to-foreach.ts
- src/refactorings/convert-if-else-to-ternary/convert-if-else-to-ternary.ts
- src/refactorings/convert-ternary-to-if-else/convert-ternary-to-if-else.ts
- src/refactorings/extract-generic-type/extract-generic-type.ts
- src/refactorings/extract/extract-variable/extract-variable.ts
- src/refactorings/extract/extract-variable/occurrence.ts
- src/refactorings/extract/extract-variable/variable.ts
- src/refactorings/inline/inline-function/inline-function.ts
- src/refactorings/inline/inline-variable/find-inlinable-code.ts
- src/refactorings/move-to-existing-file/move-to-existing-file.ts
- src/refactorings/negate-expression/negate-expression.ts
- src/refactorings/replace-binary-with-assignment/replace-binary-with-assignment.ts
- src/refactorings/split-declaration-and-initialization/split-declaration-and-initialization.ts
- src/refactorings/toggle-braces/toggle-braces.ts
- yarn.lock
I finally took the time to upgrade babel from 7.9 to the latest version (7.15), resolving the type conflicts.
A few code changes were required too. I'm glad we have a good test coverage: now I feel confident there's no regression (unless we are missing tests for these).
> Upgrade babel

- src/editor/path.ts
vscode uses `/` separator in any os
path.posix will use `/` separator in any os
Fixes #376
> changed path to use path.posix

- CHANGELOG.md
- src/refactorings/merge-if-statements/merge-if-statements.test.ts
- src/refactorings/merge-if-statements/merge-if-statements.ts
The logic was becoming complex with all the scenarios. I used a Chain of Responsibility to standardize the logic and handle all the cases smoothly.
That fixed a few bugs 👌
> Prevent "Merge If Statements" from being suggested where it can't execute

- src/action-providers.ts
- src/refactorings/toggle-braces/index.ts
- src/refactorings/toggle-braces/toggle-braces.test.ts
- src/refactorings/toggle-braces/toggle-braces.ts
Closes #247
Toggle braces now also works for
- for statements
- for in statements
- for of statements
- while statements
- do while statements
I used the alias `Loop` to implement this refactoring. This way we don't have to handle all the different kinds of loops separately. However, I also had to change the action provider to be able to handle aliases. Without this the toggle braces refactoring was not suggested for loops.
> Implement toggle braces for loops

- src/ast/transformation.ts
- src/refactorings/extract/extract-variable/occurrence.ts
- src/refactorings/react/convert-to-pure-component/convert-to-pure-component.ts
On windows, `recast` is using `\r\n` by default and this is causing a lot of test to fail
> Fix test on windows

- src/action-providers.ts
Fixes the quick action provider
`forEachToForOf` used an exit method instead of the shorthand form (babel handbook), so I added the calls
> Note: `Identifier() { ... }` is shorthand for `Identifier: { enter() { ... } }`.
Before:
After:
-----------------------
I had some trouble with getting the current version to build so I tested it on v6.8.0 (3d7cc05a06ad4015313374bb27455c7ace7e0cf6) for now
> fix: exit visitor

- .gitignore
- .vscodeignore
I just noticed that installing this extension takes forever. Published vsix is 40mb. After ignoring docs with gifs `vsce` says it is 5mb now.
ImageOptim said it is possible to save 11mb in repo. ~~However GIFs are evil and I suggest to remove them from repo and use fancy codes instead.~~ UPD: I understand there is no other way to demonstrate functionality, however I believe in some future we can use SVGs for that.
You can also [reduce bundle size](https://github.com/prettier/prettier-vscode/pull/2302#issuecomment-1003753084) with esbuild. It can also give you really fast builds!
WDYT?
Also note that it is much simpler to ignore everything in `.vscodeignore` and unignore only needed assets.
> ignore docs dir with gifs to reduce extension size

- package.json
- src/ast/transformation.ts
- src/editor/error-reason.ts
- src/extension.ts
- src/refactorings/react/extract-use-callback/extract-use-callback.test.ts
- src/refactorings/react/extract-use-callback/extract-use-callback.ts
- src/refactorings/react/extract-use-callback/index.ts
- yarn.lock
Add a new React-specific refactoring to extract an inline function from a JSX prop to a `useCallback` call.
- Arrow and function expressions
- Rename the extracted identifier if it conflicts
- Add a block if it was an arrow expression without braces
- Add types to the function
- Infer dependencies (always uses an empty array) - use the React hooks ESLint fixers for that
https://user-images.githubusercontent.com/897931/167899020-6e456b0c-6c61-4b02-abdf-449cb9ce8a68.mp4
- Unit tests
- "Run in debugger" and test on a real React file
> [New Refactoring] Extract useCallback

- src/refactorings/extract/extract-variable/extract-variable.extractable.test.ts
- src/refactorings/extract/extract-variable/extract-variable.multiple-occurrences.test.ts
- src/refactorings/extract/extract-variable/occurrence.ts
- src/refactorings/extract/extract-variable/variable.ts
When extracting a class instantiation, for instance `new ImageEditor()`, provide a more user-friendly default name (instead of `extracted`). The new default is the camel-cased class name, `imageEditor` in the example above.
> Enhance the default name for new expression

- src/ast/transformation.ts
- src/refactorings/convert-for-each-to-for-of/convert-for-each-to-for-of.test.ts
- src/refactorings/convert-for-each-to-for-of/convert-for-each-to-for-of.ts
- src/refactorings/convert-for-to-for-each/convert-for-to-for-each.test.ts
- src/refactorings/convert-for-to-for-each/convert-for-to-for-each.ts
- src/refactorings/convert-if-else-to-switch/convert-if-else-to-switch.test.ts
- src/refactorings/convert-if-else-to-switch/convert-if-else-to-switch.ts
- src/refactorings/convert-if-else-to-ternary/convert-if-else-to-ternary.test.ts
- src/refactorings/convert-if-else-to-ternary/convert-if-else-to-ternary.ts
- src/refactorings/convert-switch-to-if-else/convert-switch-to-if-else.test.ts
- src/refactorings/convert-switch-to-if-else/convert-switch-to-if-else.ts
- src/refactorings/convert-ternary-to-if-else/convert-ternary-to-if-else.test.ts
- src/refactorings/convert-ternary-to-if-else/convert-ternary-to-if-else.ts
- src/refactorings/convert-to-arrow-function/convert-to-arrow-function.ts
- src/refactorings/convert-to-template-literal/convert-to-template-literal.test.ts
- src/refactorings/convert-to-template-literal/convert-to-template-literal.ts
- src/refactorings/split-declaration-and-initialization/split-declaration-and-initialization.test.ts
- src/refactorings/split-declaration-and-initialization/split-declaration-and-initialization.ts
- src/refactorings/split-multiple-declarations/split-multiple-declarations.test.ts
- src/refactorings/split-multiple-declarations/split-multiple-declarations.ts
Fixes #705
Some refactorings deleted comments (e.g. `Split multiple declarations`) because `path.replaceWith/replaceWithMultiple` does not inherit the `comments` property added by recast. I fixed this by creating and calling `replaceWithPreservingComments/replaceWithMultiplePreservingComments` instead.
> Preserve comments when replacing nodes

- package.json
- src/editor/adapters/create-vscode-editor.ts
- src/extension.ts
- src/playground/Playground.svelte
Fixes #726 
Adds support for .svelte files. 
I piggy backed off the support for vue files, which seems to work, using this PR as a base https://github.com/nicoespeon/abracadabra/pull/157/files. 
I wasn't sure if it was worth renaming the `VueVSCodeEditor` to something more generic like `VueAndSvelteVSCodeEditor`
I havn't added in any additional tests yet but can do if required.
> feat: add svelte support

- src/editor/adapters/in-memory-editor.ts
- src/editor/editor-contract-test.ts
Verify that `getSelectionReferences` behavior is similar to what VS Code and InMemory does
It was pending from https://github.com/nicoespeon/abracadabra/pull/725#discussion_r1009994929
> Change Signature I: Add contract test for code references

- src/playground/maths/calculator.ts
- src/playground/maths/maths.ts
- src/refactorings/change-signature/change-signature.test.ts
- src/refactorings/change-signature/change-signature.ts
Hey :) 
**This PR depends on https://github.com/nicoespeon/abracadabra/pull/746**
I was able to change function signature of an arrow function, but there are some doubts when to trigger "Change signature" action.
In this iteration we shoud put the Cursor on function asignation:
But maybe we want to trigger "Change signature" over variable declaration. 
**Where do you think we should trigger it** @nicoespeon ?
> Change signature II: Handle arrow functions 

- CHANGELOG.md
- package.json
- src/editor/error-reason.ts
- src/extension.ts
- src/refactorings/flip-yoda-condition/flip-yoda-condition.test.ts
- src/refactorings/flip-yoda-condition/flip-yoda-condition.ts
- src/refactorings/flip-yoda-condition/index.ts
Closes #749 
`+`, `*`, `&`, `|`, `^` can also be flipped, but maybe the name should be changed since they're not conditions.
At least with numbers it behaves the same but I just noticed that `+` changes the order of strings when flipping.. ignore, add type checking or exclude this operator?
> Add "Flip Yoda Condition" refactoring

- package.json
- src/refactorings/create-factory-for-constructor/create-factory-for-constructor.ts
- src/refactorings/extract-interface/extract-interface.test.ts
- src/refactorings/extract/extract-type/extract-type.test.ts
- src/refactorings/extract/extract-type/extract-type.ts
- src/refactorings/extract/extract-variable/occurrence.ts
- src/refactorings/flip-if-else/flip-if-else.test.ts
- src/refactorings/flip-if-else/flip-if-else.ts
- src/refactorings/flip-operator/flip-operator.test.ts
- src/refactorings/move-statement-up/move-statement-up.ts
- src/refactorings/react/extract-use-callback/extract-use-callback.test.ts
- src/refactorings/split-if-statement/split-if-statement.test.ts
- src/refactorings/toggle-braces/toggle-braces.test.ts
- yarn.lock
Turns out this was an issue with Recast. Upgrading the dependencies fixed that.
I added a test to capture this scenario. I noticed this change may add new parens that are not necessarily required, but that's less important than having broken code (if you have Prettier, they will be auto-trimmed).
Close #753
> Fix "Flip If/Else" that was removing parentheses

- src/refactorings/change-signature/change-signature.test.ts
- src/refactorings/change-signature/change-signature.ts
Hide "Change signature" for function/method without parameters
Error:
New:
Even for React Components
Error:
New
> Do not show 'Change signature' quick fix when a function/method does not has parameters

- src/refactorings/change-signature/change-signature.test.ts
- src/refactorings/change-signature/change-signature.ts
I just installed this extension, and notice the function refactor does not work in some cases.
I add a unit test to emphasis this behavior, which I consider being a bug.
The case is simple: when a function call statement contains new lines (example: one argument on its each line), the refactor (re-order args or remove arg) does not work.
1. Given the following code:
```js
function /*[cursor]*/doWhatever(prefix, obj) {
console.log(obj);
}
doWhatever("will be removed", "foo");
doWhatever(
"will NOT be removed",
"foo"
);
```
2. put cursor at `/*[cursor]*/` position
3. trigger "Change signature" tool
4. select `prefix` in the table shown
5. click "minus sign" to remove the `prefix` argument
6. click `confirm` to validate changes
I expect:
1. the function declaration to be changed
2. the first …
> add new test for function refactoring with new lines

- CHANGELOG.md
- README.md
- REFACTORINGS.md
- package.json
- src/editor/adapters/vscode-editor.ts
- src/editor/editor.ts
- src/extension.ts
- src/refactorings/convert-to-template-literal/convert-to-template-literal.test.ts
- src/refactorings/convert-to-template-literal/convert-to-template-literal.ts
- yarn.lock
When adding `${}` in a valid String literal.
It can be disabled in the settings (`abracadabra.autoConvertToTemplateLiteral`) because it's technically not a refactoring—but in most scenarios, this is what we want to do.
It does not handle multi-cursors because the original refactoring doesn't (in fact, none of the refactorings we have support this for now). I think that's OK.
I was considering handling more scenarios, like adding $ to `{someValue}` in a string would also trigger the refactoring… but these don't seem to be the main use-case and may not actually be desirable (again, technically we are modifying the behavior of the code here). So I rollback and stick to the basic one: 
https://github.com/nicoespeon/abracadabra/assets/1094774/476e4755-551c-4446-aa8d-e4552626528e
As usual, I'll …
> Automatically trigger "Convert to Template Literal"

- .github/workflows/ovsx-deploy.yml
- .github/workflows/tests.yml
- .github/workflows/vscode-deploy.yml
- package.json
Dependencies updates start failing because we rely on Node 18 that will be EOL in less than a year. Let's upgrade to Node 20 at least, or see if we could push to Node 22 (the current version).
> Upgrade Node to v20

- .vscode/extensions.json
- .vscode/settings.json
Small DX improvement.
There's precommit hook to format code with Prettier, but we can make it easier for devs to use Prettier sooner, when they write code
> chore: add Prettier plugin to workspace recommended plugins, set as default formatter

- CHANGELOG.md
- src/editor/adapters/vscode-editor.ts
Extracting a variable (`Ctrl + Alt + V` / `⌥ ⌘ V`) while selecting a portion of the value may result in a partial selection when you get to name the extracted variable. Annoying! 
Not anymore… The whole identifier is now selected, so you can just write the name right away 😉
https://github.com/user-attachments/assets/af28217a-f220-4d76-b905-e22e09967db1 
https://github.com/user-attachments/assets/d105b73d-e0b0-4f42-b838-ccca8633bcb0
> Fix the selection when extracting a variable
